### ISSUE TITLE
Upgrade to JakartaEE

### ISSUE THREAD

**Issue by fschon** [opencrx/opencrx#124]
Code does not compile under JakartaEE.

**Comment by fschon** [comment]
Hi Werner.
Circling back to this issue, I need to urgently upgrade my codebase to JakartaEE10 as javax is just no longer viable. Are there any plans to support Jakarta EE10 and remove all references to javax? 
One immediate issue I see is I cannot find a jakarta upgrade for JDO.

**Comment by fschon** [comment]
Actually I think the Apache JDO API 3.2.1 might be free of old Javaee references. I have changed all references of other legacy javaee javax references to jakarta in the openmdx codebase, but I keep coming up with hidden references that I just cannot find I have searched the entire codebase for any file type containing javax. The current error I am getting is:

> > Task :core:generate-model FAILED
Exception in thread "main" java.lang.NoClassDefFoundError: javax/resource/cci/Connection
        at org.openmdx.application.mof.externalizer.spi.ModelExternalizer_1.<init>(ModelExternalizer_1.java:91)
        at org.openmdx.application.mof.externalizer.xmi.XMIExternalizer.<init>(XMIExternalizer.java:123)
        at org.openmdx.application.mof.externalizer.xmi.XMIExternalizer.main(XMIExternalizer.java:181)
Caused by: java.lang.ClassNotFoundException: javax.resource.cci.Connection
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
        ... 3 more

I can't find any javax.resource.cci.Connection references anywhere or any libraries that may use it. Can you maybe point me in the direction where these references might be coming from please.

**Comment by wfro64** [comment]
The support of JavaEE for openCRX requires that openMDX supports JavaEE. This is currently not the case. Please create a corresponding ticket in the openMDX project https://github.com/openmdx/openmdx/issues
