### ISSUE TITLE
initPrincipalGroup() call fails when using a REST persistence manager

### ISSUE THREAD

**Issue by fschoning** [opencrx/opencrx#146]
The following code fails when using the REST connected PM, but works when using the jar files directly.

`SecureObject.getInstance().initPrincipalGroup("CustomerPortalUsers", pm, "CRX", "Demo")`

The error is:

> org.openmdx.base.accessor.jmi.cci.JmiServiceException: org.openmdx.base.exception.ServiceException: DefaultDomain.DUPLICATE
>     BasicException[0]
> Class = org.openmdx.base.accessor.rest.DataObject_1
> Method = objMove
> Line = 1434
> ExceptionClass = org.openmdx.base.exception.ServiceException
> ExceptionDomain = DefaultDomain
> ExceptionCode = DUPLICATE
> Description = There is already an object with the same qualifier in the container
> Timestamp = 2024-12-06T09:34:33.056Z

**Comment by wfro64** [comment]
Classes / Methods / Logic in package  org.opencrx.kernel.backend.* are designed to be used in backend-context only. They  should not be used in client-context and usually do not work. Clients should access backend-logic only via the (modeled) API.

**Comment by wfro64** [comment]
In order to create a PrincipalGroup you can try using the method Admin.createPrincipal(). It should work in client-context:
* the run-as user of the pm must be the segment-admin, e.g. "admin-Standard" --> pmAdmin
* all params (realm, memberOfGroups, subject) must be retrieved with pmAdmin.getObjectById()
* subject is optional for PrincipalGroups but should be provided, e.g. admin-Standard

**Comment by wfro64** [comment]
Also see https://github.com/opencrx/opencrx/issues/147

**Comment by fschoning** [comment]
> In order to create a PrincipalGroup you can try using the method Admin.createPrincipal(). It should work in client-context:
> 
> * the run-as user of the pm must be the segment-admin, e.g. "admin-Standard" --> pmAdmin
> * all params (realm, memberOfGroups, subject) must be retrieved with pmAdmin.getObjectById()
> * subject is optional for PrincipalGroups but should be provided, e.g. admin-Standard

Hi Werner.
This was initially my first approach I tried, however I get an error when making the call.

```
Admin.register();
PrincipalGroup customerPortalPrincipalGroup = (PrincipalGroup) Admin.getInstance().createPrincipal(
    principalGroupId,
    principalGroupId,
    principalGroupId,
    realm,
    Admin.PrincipalType.GROUP,
    new ArrayList<Group>(),
    subject);
```

> [main] ERROR functiontests.TestPrincipalGroups - DefaultDomain.DUPLICATE: There is already an object with the same qualifier in the container
> org.openmdx.base.accessor.jmi.cci.JmiServiceException: org.openmdx.base.exception.ServiceException: DefaultDomain.DUPLICATE
>     BasicException[0]
> 	Class = org.openmdx.base.accessor.rest.DataObject_1
> 	Method = objMove
> 	Line = 1431
> 	ExceptionClass = org.openmdx.base.exception.ServiceException
> 	ExceptionDomain = DefaultDomain
> 	ExceptionCode = DUPLICATE
> 	Description = There is already an object with the same qualifier in the container
> 	Timestamp = 2025-01-13T16:17:47.758Z
> 	Parameters:
> 	    0:	xri = xri://@openmdx*org.openmdx.security.realm1/provider/CRX/segment/Root/realm/Demo/principal/CustomerPortalUsersTest2
> 	StackTrace:
> 	    at org.openmdx.base.accessor.rest.DataObject_1.objMove(DataObject_1.java:1431)
> 	    at org.openmdx.base.accessor.spi.DelegatingObject_1.objMove(DelegatingObject_1.java:295)
> 	    at org.openmdx.base.accessor.spi.DelegatingObject_1.objMove(DelegatingObject_1.java:295)
> 	    at org.openmdx.base.accessor.spi.DelegatingObject_1.objMove(DelegatingObject_1.java:295)
> 	    at org.openmdx.base.accessor.spi.MarshallingObject_1.objMove(MarshallingObject_1.java:405)
> 	    at org.openmdx.base.accessor.jmi.spi.RefObject_1.refAddValue(RefObject_1.java:1579)
> 	    at org.openmdx.base.accessor.jmi.spi.Jmi1ObjectInvocationHandler.invoke(Jmi1ObjectInvocationHandler.java:575)
> 	    at jdk.proxy2/jdk.proxy2.$Proxy7.addPrincipal(Unknown Source)
> 	    at org.opencrx.kernel.backend.Admin.createPrincipal(Admin.java:401)
